---
# defaults file for nsxv-cluster-prep
nsxmanager_spec:
  raml_file: '/path/to/nsxraml/nsxvapi.raml'
  host: 'nsx-manager.local'
  user: '{{ vault_nsxv_username }}'
  password: '{{ vault_nsxv_password }}'

vcenter_hostname: 'vcenter.local'
vcenter_username: '{{ vault_vcenter_username }}'
vcenter_password: '{{ vault_vcenter_password }}'
vcenter_datacenter: 'datacenter'
vcenter_cluster: 'cluster'
vcenter_dvs: 'dvSwitch'

nsxv_cluster_state: present

vtep:
  vlan_id: 102
  vmknic_count: 1
  teaming: 'LOADBALANCE_SRCID'
  mtu: 9000