---
# defaults file for esxi-services
esxi_username: '{{ vault_esxi_username }}'
esxi_password: '{{ vault_esxi_password }}'

service_list:
  - name: ntpd
    policy: on
    state: start
  - name: TSM-SSH
    policy: on
    state: start