---
# defaults file for nsxv-controllers
nsxmanager_spec:
  raml_file: '/path/to/nsxraml/nsxvapi.raml'
  host: 'nsx-manager.local'
  user: '{{ vault_nsxv_username }}'
  password: '{{ vault_nsxv_password }}'

vcenter_hostname: 'vcenter.local'
vcenter_username: '{{ vault_vcenter_username }}'
vcenter_password: '{{ vault_vcenter_password }}'
vcenter_datacenter: 'datacenter'
vcenter_datastore: 'vsanDatastore'
vcenter_cluster: 'cluster'

controller_portgroup: 'portgroup'
controller_pool_state: true
controller_state: present
controller_name_prefix: 'prefix-'
controller_password: '{{ vault_controller_password }}'

syslog_server: 'syslog.local'

controller_ippool:
  name: controller_ippool
  start_ip: '192.168.0.251'
  end_ip: 192.168.253'
  prefix_length: '24'
  gw: '192.168.0.254'
  dns1: '8.8.8.8'
  dns2: '8.8.4.4'