---
# tasks file for esxi-services

- name: Interface with ESXi services
  vmware_host_service_manager:
    esxi_hostname: '{{ inventory_hostname }}'
    username: '{{ esxi_username }}'
    password: '{{ esxi_password }}'
    validate_certs: false
    service_name: '{{ item.name }}'
    service_policy: '{{ item.policy }}'
    state: '{{ item.state }}'
  with_items: '{{ service_list }}'
