---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - sddc_vars.yml

  tasks:
    - name: Gather ESXi services status
      vmware_host_service_facts:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: False
        cluster_name: '{{ cluster }}'
      register: cluster_host_services