vcenter_hostname: "usa1-2-vcenter.oc.vmware.com"
vcenter_username: "administrator@vsphere.local"
vcenter_password: ""

nsxmanager_spec:
        raml_file: '/opt/nsxraml/nsxvapi.raml'
        host: 'usa1-2-nsxv.oc.vmware.com'
        user: 'admin'
        password: ''

datacenter: "Ansible-Datacenter"
cluster: "Ansible-Cluster"

esxi_username: "root"
esxi_password: ""

domain: "oc.vmware.com"
dns_servers:
  - 10.128.242.1
  - 10.128.242.2
search_path:
  - oc.vmware.com
  - eng.vmware.com
  - vmware.com

cluster_ha: "yes"
cluster_drs: "yes"
cluster_vsan: "no"

esxi_hostlist:
  - usa1-3-esx1.oc.vmware.com
  - usa1-3-esx2.oc.vmware.com
  - usa1-3-esx3.oc.vmware.com
  - usa1-3-esx4.oc.vmware.com

service_list:
  - TSM-SSH
  - ntpd

dvs_name: "dvSwitch-Ansible"
dvs_version: "6.6.0"
dvs_mtu: "9000"
dvs_uplinks: "2"
dvs_discovery_proto: "cdp"
dvs_discovery_op: "both"
dvs_mgmt_pg: "dpgManagement-141"
dvs_mgmt_vmk: "vmk0"

vmnics:
  - vmnic3

vss_name: "vSwitch0"
vss_portgroup: "Management Network"

portgroups:
  - name: "dpgManagement-131"
    vlan_id: "131"
    num_ports: "120"
    portgroup_type: "ephemeral"
  - name: "dpgManagement-141"
    vlan_id: "141"
    num_ports: "120"
    portgroup_type: "ephemeral"
  - name: "VSAN"
    vlan_id: "132"
    num_ports: "120"
    portgroup_type: "ephemeral"
  - name: "vMotion"
    vlan_id: "133"
    num_ports: "120"
    portgroup_type: "ephemeral"

esx1_vmk_vmotion:
  portgroup: "vMotion"
  vlan_id: "133"
  vmk_net_type: "static"
  vmk_ip_addr: "172.17.2.41"
  vmk_subnet: "255.255.255.224"
  mtu: "1500"
  enable_ft: False
  enable_mgmt: False
  enable_vmotion: True
  enable_vsan: False

esx2_vmk_vmotion:
  portgroup: "vMotion"
  vlan_id: "133"
  vmk_net_type: "static"
  vmk_ip_addr: "172.17.2.42"
  vmk_subnet: "255.255.255.224"
  mtu: "1500"
  enable_ft: False
  enable_mgmt: False
  enable_vmotion: True
  enable_vsan: False

esx3_vmk_vmotion:
  portgroup: "vMotion"
  vlan_id: "133"
  vmk_net_type: "static"
  vmk_ip_addr: "172.17.2.43"
  vmk_subnet: "255.255.255.224"
  mtu: "1500"
  enable_ft: False
  enable_mgmt: False
  enable_vmotion: True
  enable_vsan: False

esx4_vmk_vmotion:
  portgroup: "vMotion"
  vlan_id: "133"
  vmk_net_type: "static"
  vmk_ip_addr: "172.17.2.44"
  vmk_subnet: "255.255.255.224"
  mtu: "1500"
  enable_ft: False
  enable_mgmt: False
  enable_vmotion: True
  enable_vsan: False

esx1_vmk_vsan:
  portgroup: "VSAN"
  vlan_id: "132"
  vmk_net_type: "static"
  vmk_ip_addr: "172.17.2.9"
  vmk_subnet: "255.255.255.224"
  mtu: "1500"
  enable_ft: False
  enable_mgmt: False
  enable_vmotion: False
  enable_vsan: True

esx2_vmk_vsan:
  portgroup: "VSAN"
  vlan_id: "132"
  vmk_net_type: "static"
  vmk_ip_addr: "172.17.2.10"
  vmk_subnet: "255.255.255.224"
  mtu: "1500"
  enable_ft: False
  enable_mgmt: False
  enable_vmotion: False
  enable_vsan: True

esx3_vmk_vsan:
  portgroup: "VSAN"
  vlan_id: "132"
  vmk_net_type: "static"
  vmk_ip_addr: "172.17.2.11"
  vmk_subnet: "255.255.255.224"
  mtu: "1500"
  enable_ft: False
  enable_mgmt: False
  enable_vmotion: False
  enable_vsan: True

esx4_vmk_vsan:
  portgroup: "VSAN"
  vlan_id: "132"
  vmk_net_type: "static"
  vmk_ip_addr: "172.17.2.12"
  vmk_subnet: "255.255.255.224"
  mtu: "1500"
  enable_ft: False
  enable_mgmt: False
  enable_vmotion: False
  enable_vsan: True
