---
# defaults file for nsxv-transport-zone
nsxmanager_spec:
  raml_file: '/path/to/nsxraml/nsxvapi.raml'
  host: 'nsx-manager.local'
  user: '{{ vault_nsxv_username }}'
  password: '{{ vault_nsxv_password }}'

vcenter_hostname: 'vcenter.local'
vcenter_username: '{{ vault_vcenter_username }}'
vcenter_password: '{{ vault_vcenter_password }}'

transport_zone:
  name: 'transport-zone'
  state: present
  control_plane: 'UNICAST_MODE'
  description: 'default transport-zone'

cluster_list:
  - 'cluster01'
  - 'cluster02'