# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
#
# You may obtain a copy of the License at
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Author: Chris Mutchler (chris@virtualelephant.com)
#
# Description:
#   Playbook will configure a set of ESXi hosts.
#
# Note:
#   Use of the virtualelephant/ubuntu-ansible Docker container will include
#   all of necessary Ansible modules and libraries necessary to execute the
#   playbook.
---
- hosts: esxi-nodes
  connection: local
  gather_facts: false

  vars:
    vcenter_hostname: 'vcenter.local'
    vcenter_username: '{{ vault_vcenter_username }}'
    vcenter_password: '{{ vault_vcenter_password }}'
    vcenter_datacenter: 'datacenter'
    vcenter_datastore: 'vsanDatastore'
    vcenter_cluster: 'cluster'
    vcenter_dvs: 'dvSwitch'

    esxi_username: '{{ vault_esxi_username }}'
    esxi_password: '{{ vault_esxi_password }}'

    domain_name: 'local.domain'

    dns_servers:
      - 8.8.8.8
      - 8.8.4.4
    ntp_servers:
      - 132.163.96.5
      - 132.163.97.5

    change_hostname: false
    ntp_state: present

  roles:
    - esxi-host-config
    - esxi-adv-settings
    - esxi-services
    - esxi-vmk-interfaces
